### ISSUE TITLE
parse exception thrown from `stop` command

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#152]
FormatException: Invalid radix-10 number
1864
4050

```
Exception:
#0      int._throwFormatException (dart:core-patch/integers_patch.dart:111)
#1      int._parse (dart:core-patch/integers_patch.dart:101)
#2      int.parse (dart:core-patch/integers_patch.dart:58)
#3      AndroidDevice.stopApp.<stopApp_async_body> (package:sky_tools/src/device.dart:847)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#6      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by devoncarew** [comment]
From @krisgiesing on the closed issue:

> It looks to me like there is more than one process that matches the 'lsof' call that AndroidDevice.stopApp() is trying to find, and the code isn't expecting the newline.
