### ISSUE TITLE
Demo app crashes on first launch

### ISSUE THREAD

**Issue by YourCyborg** [flutter/tools#177]
It shows the hello world demo app, and then it crashes. Subsequent 'flutter start' attempts do not result in crashes, and the demo app seems to display as intended.

Logs and the app have been deleted between attempts - reproduced each time.

Computer: Elementary/Freya, based on Ubuntu 14.04 

Android: 5.0.2, Nexus 7 Model ME370T

~/Android/my_app$ flutter logs
android: --------- beginning of main
android: --------- beginning of system
android: W/chromium: [WARNING:asset_bundle_impl.cc(45)] Requested asset 'content/drawable-xxhdpi/ic_add_white_24dp.png' does not exist.
android: --------- beginning of crash
android: F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 7673 (io_thread)
android: W/ActivityManager:   Force finishing activity org.domokit.sky.shell/.SkyActivity
android: W/ActivityManager: Exception thrown during pause
android: W/ActivityManager: android.os.DeadObjectException
android: W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
android: W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:496)
android: W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:701)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:852)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2754)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2611)
android: W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2453)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11511)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11408)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12087)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11603)
android: W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by devoncarew** [comment]
Something you may want to try is to create a `flutter.yaml` file in the root of your project, with this content:

```yaml
name: _project_name_
material-design-icons:
  - name: content/add
```

And you'll want to substitute the name of your project with the first name: field above.

**Comment by YourCyborg** [comment]
Yeah, that works.

Any actual project beyond the demo wouldn't run into this issue (I hope). It looks like this boiler plate code needs to be added so that the '[Getting Started](http://flutter.io/getting-started/)' instructions don't result in a crash. It's ambiguous to developers fresh to the project (me anyways) who are just trying to get a basic setup that doesn't [crash](https://groups.google.com/forum/#!topic/flutter-dev/GMotmRvYKJI) (my last crash resulted in me having to switch devices) from point A to point B before truly diving in

**Comment by devoncarew** [comment]
Yup, this is a regression in our sample app, and unfortunate in that users very new to the platform hit it.

Glad to hear that this gets things working for you though! We've updated the `flutter init` sample and will make sure other samples are up to date.
