### ISSUE TITLE
Tools should support Windows hosts

### ISSUE THREAD

**Issue by abarth** [flutter/tools#36]
See https://groups.google.com/d/msg/sky-dev/mDgJ0zomhkA/O-ZFwhXlEwAJ for context.

**Comment by abarth** [comment]
See also https://github.com/flutter/engine/issues/771

**Comment by TheBosZ** [comment]
+1

I dev primarily on Windows and would love to be able to use this.

**Comment by TheBosZ** [comment]
With the close of flutter/engine#362 the next thing that stops me is I don't have shasum:

```
dart\flutter-test>flutter start --checked
Downloading https://storage.googleapis.com/mojo/sky/shell/android-arm/7980151329
165fda67ae03977105d37ec1d8e73e/SkyShell.apk to packages\sky_tools\cache\sky_engi
ne\7980151329165fda67ae03977105d37ec1d8e73e\Release\SkyShell.apk.
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: shasum -a 1 -p packages\sky_tools\cache\sky_engine\7980151329165fda67
ae03977105d37ec1d8e73e\Release\SkyShell.apk
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:449)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:603)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      _runWithLoggingSync (package:sky_tools/src/process.dart:70)
#4      runCheckedSync (package:sky_tools/src/process.dart:62)
#5      AndroidDevice._getSourceSha1 (package:sky_tools/src/device.dart:699)
#6      AndroidDevice.isAppInstalled (package:sky_tools/src/device.dart:714)
#7      InstallCommand.install (package:sky_tools/src/commands/install.dart:34)
#8      StartCommand.run.<run_async_body> (package:sky_tools/src/commands/start.
dart:51)
#9      _RootZone.runUnary (dart:async/zone.dart:1149)
#10     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#11     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#12     _Future._complete (dart:async/future_impl.dart:366)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#14     FlutterCommand.downloadApplicationPackagesAndConnectToDevices.<downloadA
pplicationPackagesAndConnectToDevices_async_body> (package:sky_tools/src/command
s/flutter_command.dart)
#15     _RootZone.runUnary (dart:async/zone.dart:1149)
#16     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#17     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#18     _Future._complete (dart:async/future_impl.dart:366)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#20     FlutterCommand.downloadApplicationPackages.<downloadApplicationPackages_
async_body> (package:sky_tools/src/commands/flutter_command.dart)
#21     _RootZone.runUnary (dart:async/zone.dart:1149)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#24     _Future._complete (dart:async/future_impl.dart:366)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#26     ApplicationPackageStore.forConfigs.<forConfigs_async_body> (package:sky_
tools/src/application_package.dart)
#27     _RootZone.runUnary (dart:async/zone.dart:1149)
#28     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#29     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#30     _Future._complete (dart:async/future_impl.dart:366)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#32     ArtifactStore.getPath.<getPath_async_body> (package:sky_tools/src/artifa
cts.dart)
#33     _RootZone.runUnary (dart:async/zone.dart:1149)
#34     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#35     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#36     _Future._complete (dart:async/future_impl.dart:366)
#37     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#38     ArtifactStore._downloadFile.<_downloadFile_async_body> (package:sky_tool
s/src/artifacts.dart)
#39     _RootZone.runUnary (dart:async/zone.dart:1149)
#40     _Future._propagateToListeners.handleValueCallback (dart:async/future_imp
l.dart:502)
#41     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#42     _Future._completeWithValue (dart:async/future_impl.dart:376)
#43     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:
430)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#45     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:151)
Unhandled exception:
ProcessException: The system cannot find the file specified.
```

**Comment by abarth** [comment]
Currently the Dart version shells out to a bunch of command line programs.  We should probably just implement that functionality in dart itself.  For example, computing the sha1sum of a file should be pretty easy in Dart.

**Comment by TheBosZ** [comment]
I'd love to contribute this, but I'm not sure how to test it.

I've cloned the code and made the change on my computer, but no matter how I try to invoke the 'install' action, I get errors. How do I invoke the install action?

**Comment by abarth** [comment]
What errors do you get?  It might be easier to talk this through in IRC.  I'm on #flutter on freenode if you want to chat.
