### ISSUE TITLE
when running `sky_tools init` I see this error

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#70]
```
SEVERE: Unexpected failure from adb: 
Error code 255 returned when attempting to run command: adb shell getprop ro.build.version.sdk
#0      _runWithLoggingSync (package:sky_tools/src/process.dart:52)
#1      runCheckedSync (package:sky_tools/src/process.dart:34)
#2      AndroidDevice._checkForLollipopOrLater (package:sky_tools/src/device.dart:209)
#3      AndroidDevice.AndroidDevice._ (package:sky_tools/src/device.dart:126)
#4      _Device._Device.<anonymous closure> (package:sky_tools/src/device.dart:34)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:254)
#6      _Device._Device (package:sky_tools/src/device.dart:32)
#7      AndroidDevice.AndroidDevice (package:sky_tools/src/device.dart:77)
#8      InstallCommand.InstallCommand (package:sky_tools/src/install.dart:20)
#9      main (http://localhost:57591/sky_tools.dart:154)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
SEVERE: Unable to run on Android.
Creating odd_limit_0749...
```

on the latest version (`0.0.16`)

**Comment by devoncarew** [comment]
This is also the case for running the help commands:

```
[~/flutter/old_silence_5244] sky_tools init -h
SEVERE: Unexpected failure from adb: 
Error code 255 returned when attempting to run command: adb shell getprop ro.build.version.sdk
#0      _runWithLoggingSync (package:sky_tools/src/process.dart:52)
#1      runCheckedSync (package:sky_tools/src/process.dart:34)
#2      AndroidDevice._checkForLollipopOrLater (package:sky_tools/src/device.dart:209)
#3      AndroidDevice.AndroidDevice._ (package:sky_tools/src/device.dart:126)
#4      _Device._Device.<anonymous closure> (package:sky_tools/src/device.dart:34)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:254)
#6      _Device._Device (package:sky_tools/src/device.dart:32)
#7      AndroidDevice.AndroidDevice (package:sky_tools/src/device.dart:77)
#8      InstallCommand.InstallCommand (package:sky_tools/src/install.dart:20)
#9      main (http://localhost:57847/sky_tools.dart:154)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

SEVERE: Unable to run on Android.
Create a new Flutter project.
```

**Comment by iansf** [comment]
Do you have more than one android device connected?

**Comment by devoncarew** [comment]
Just the one, but it looks like the install command tries to find android devices in its ctor. It probably shouldn't try and do this until the command is actually invoked. I can put together a PR.
